### ISSUE TITLE
Timer going slow when the gamespeed is lower than at 60fps

### ISSUE THREAD

**Issue by TeamSoldierNub2** [LDinos/Dijeweled#2]
I'm on PC, opponent is on mobile

My timer ends, but theirs is still going

I tested this a few times, turns out their device was running slow, and the timer was going slower for them than it was for me.

**Comment by LDinos** [comment]
Thanks for the report! Yeah this might happen, the timer works on each client differently so if someone is lagging and playing in slow-mo, the timer will also be on slow-mo (especially with mobile, which is know to lag a lot with Dijeweled)
