### ISSUE TITLE
FATAL ERROR in Room Creation Code for room rm_loading_menu

### ISSUE THREAD

**Issue by YalekW5435** [LDinos/Dijeweled#25]
It was not set before reading it, according to the IDE v2023.2.1.75 with runtime  v2023.2.1.90.  This happens after the app is built and attempts to load the main menu.  all other code is 100% functional, except this.  
Windows 11 insider preview build (a release, not an actual beta version) 10.0.22631.1835.  Im pretty sure build version would not matter, anyways.  
Using a AMD Ryzen 5700G with radeon graphics.  1TB SSD... All other code is functional...

**Comment by LDinos** [comment]
Hello, this is due to an update in gamemaker where if you use x,y variables in room creation code, it will throw this error. For every x or y you see in room creation code, convert it to 0 instead.
example:
instance_create(x,y,obj_graphics) -> instance_create(0,0,obj_graphics)

**Comment by YalekW5435** [comment]
thanks Deeno!!
